# MainPage Elements
naver_search_field = '//div[@class="search_group"]'
account_container = '//div[@id="account"]'
login_info_text = '//div[@id="account"]/div/p'
login_button = '//div[@id="account"]/div/a'
login_find_id = '//a[contains(text(), "아이디 찾기")]'
login_find_password = '//a[contains(text(), "비밀번호 찾기")]'
login_register = '//a[contains(text(), "회원가입")]'
service_icon_type_cafe = '//span[@class="service_icon type_cafe"]'
service_icon_type_blog = '//span[@class="service_icon type_blog"]'
service_icon_type_shopping = '//span[@class="service_icon type_shopping"]'
service_icon_type_news = '//span[@class="service_icon type_news"]'
service_icon_type_stock = '//span[@class="service_icon type_stock"]'
service_icon_type_real = '//span[@class="service_icon type_real"]'
service_icon_type_map = '//span[@class="service_icon type_map"]'
service_icon_type_webtoon = '//span[@class="service_icon type_webtoon"]'
cafe_main_logo = '//h1[@class="logo"]'
blog_main_logo = '//h1[@class="logo_naver_blog"]'
shopping_main_logo = '//h1[@class="_gnbLogo_title_1xWf-"]'
news_main_logo = '//div[@class="Ngnb_left"]'
stock_main_logo = '//div[@class="logo_area"]'
real_main_logo = '//div[@class="logo_area NE=a:STA"]'
map_main_logo = '//h1[@class="logo_box"]'
webtoon_main_logo = '//h1[@class="BrandBar__logo_area--Y_7dM"]'

# LoginPage Elements
login_page_logo = '//a[@class="logo"]'
id_input_field = '//input[@id="id"]'
password_input_field = '//input[@id="pw"]'
login_page_button = '//button[@id="log.login"]'
error_message = '//div[@class="error_message"]'